main: me.refrac.linkscore.Main
name: LinksCore
version: 1.3
author: Refrac

commands: 
   links:
      description: Main command
   discord: 
      description: Shows the server Discord
   website: 
      description: Shows the server Website/Forums
      aliases: [site, forums]
   store: 
      description: Shows the server Store
   staffchat: 
      description: Enable or Disable StaffChat
      aliases: [sc, sctoggle]