# Links v2
# Support Discord: https://discord.com/invite/mUKjWZByzQ
# Placeholders (PlaceholderAPI is supported for all of the Join Messages)
# {player} - Get the players name
# {displayname} - Get the players displayname
# {joinnumber} - Get the players unique join number

configVersion: 2.4
# DO NOT CHANGE PLEASE.

Update:
  Enabled: true
# Enables if there is a message on-join when the plugin is outdated.

SilentStart:
  Enabled: false
# Removes startup messages.

# Join Messages
Messages:
  # Enable or disable all join messages
  enabled: true
  join_motd:
    - "&7&m----------------------------------------------------"
    - ""
    - "     &eWelcome &d{player}&7, &eto &d&lSERVERNAME&e!"
    - ""
    - " &eWebsite: &dhttps://yourserver.net"
    - " &eDiscord: &dhttps://discord.gg/yourserver"
    - " &eTeamspeak: &dts.yourserver.net"
    - " &eStore: &dhttps://store.yourserver.net"
    - " &eTwitter: &dhttps://twitter.com/yourserver"
    - ""
    - "&7&m----------------------------------------------------"
  # What should the messages be?
  first_join_message: "&eWelcome &d{player}, &eto &d&lSERVERNAME&e! #{joinnumber}"
  join_message: "&d{player} &ejoined."
  silent_join_message: "&eWelcome back, &d{player}&e."
  quit_message: "&c{player} &eleft."
  silent_quit_message: "&eGoodbye, &d{player}&e."
  # Message for /links reload
  reload_message: "&eConfig files successfully reloaded. Changes should be live in-game!"
  no_permission: "&cSorry you don't have permission!"

# Links
# Add more with this: - ""
Links:
  - "&7&m----------------------------------------------------"
  - "                 &d&lSERVERNAME &eLinks"
  - ""
  - "&eWebsite: &dhttps://yourserver.net"
  - "&eDiscord: &dhttps://discord.gg/yourservercode"
  - "&eTeamspeak: &dts.yourserver.net"
  - "&eStore: &dhttps://store.yourserver.net"
  - "&eTwitter: &dhttps://twitter.com/yourserver"
  - ""
  - "&7&m----------------------------------------------------"

GUI:
  Enabled: true
  Title: "&d&lLinks"
  Rows: 4 # 1 = 9, 2 = 18, 3 = 27, 4 = 36, 5 = 45, 6 = 54
  WebsiteLink: "&eWebsite: &dhttps://yourserver.net"
  DiscordLink: "&eDiscord: &dhttps://discord.gg/yourservercode"
  TeamspeakLink: "&eTeamspeak: &dts.yourserver.net"
  StoreLink: "&eStore: &dhttps://store.yourserver.net"
  TwitterLink: "&eTwitter: &dhttps://twitter.com/yourserver"

WebsiteItem:
  Enabled: true
  MATERIAL: BOOK
  NAME: "&eWebsite"
  SLOT: 11
  LORE:
  - "&7L-Click to view our Website."
DiscordItem:
  Enabled: true
  MATERIAL: BOOK
  NAME: "&eDiscord"
  SLOT: 12
  LORE:
  - "&7L-Click to view our Discord."
TeamspeakItem:
  Enabled: true
  MATERIAL: BOOK
  NAME: "&eTeamspeak"
  SLOT: 13
  LORE:
  - "&7L-Click to view our Teamspeak."
StoreItem:
  Enabled: true
  MATERIAL: BOOK
  NAME: "&eStore"
  SLOT: 14
  LORE:
  - "&7L-Click to view our Store."
TwitterItem:
  Enabled: true
  MATERIAL: BOOK
  NAME: "&eTwitter"
  SLOT: 15
  LORE:
  - "&7L-Click to view our Twitter."
AllLinksItem:
  Enabled: true
  MATERIAL: DIAMOND_BLOCK
  NAME: "&eLinks"
  SLOT: 31
  LORE:
  - "&7L-Click to view all of our links."
