# LinksCore Version: 1.9
# Support Discord: https://discord.io/RefracDev
# Placeholders
# {player} - Get the players name
# {displayname} - Get the players nickname
# {arrowright} - Unicode arrow
# {circle} - Unicode circle/bullet

# This is a debug option for the developers to use to help fix an issue easier
Debug:
  # Do you want it enabled or not?
  enabled: true

# Messages
Messages:
  enabled: true
  join_motd:
    - "&7&m----------------------------------------------------"
    - ""
    - "     &eWelcome &d{player}&7, &eto &cSERVER&e!"
    - ""
    - " &e{circle} Website: &dhttps://yourserver.net"
    - " &e{circle} Discord: &dhttps://discord.gg/yourserver"
    - " &e{circle} Store: &dhttps://store.yourserver.net"
    - " &e{circle} Twitter: &dhttps://twitter.com/yourserver"
    - ""
    - "&7&m----------------------------------------------------"
  # What should the messages be?
  first_join_message: "&eWelcome &d{player}, &eto &dSERVER&e!"
  join_message: "&d{player} &ehas joined."
  silent_join_message: "&eWelcome back, &d{player}&e."
  quit_message: "&c{player} &ehas left."
  silent_quit_message: "&eGoodbye, &d{player}&e."
  no_permission: "&cSorry you don't have permission!"

# Links
# Add more with this: - ""
Links:
  - "&7&m----------------------------------------------------"
  - ""
  - "&e{circle} Website: &dhttps://yourserver.net"
  - "&e{circle} Discord: &dhttps://discord.gg/yourserver"
  - "&e{circle} Store: &dhttps://store.yourserver.net"
  - "&e{circle} Twitter: &dhttps://twitter.com/yourserver"
  - ""
  - "&7&m----------------------------------------------------"