# LinksCore Version: 1.6
configVersion: 1.6
# PLEASE DO NOT CHANGE THIS
# Discord: https://discord.io/RefracDev

# Updater
# Permission: links.update

# Change to false if you don't want to see if there's an update on-join
Update:
  Enabled: true
# Enables if there is a message on-join when the plugin is outdated.

# Messages

Prefix: "&e&l&oYour&f&l&oServer"
# The Prefix will be displayed before all of these except NoConsole & Reload
Discord: "{prefix} &e&lDiscord: &fhttps://discord.gg/yourserver"
TS: "{prefix} &e&lTeamSpeak: &fts.yourserver.net"
Website: "{prefix} &e&lWebsite: &fhttps://yourserver.net/"
Store: "{prefix} &e&lStore: &fhttps://store.yourserver.net/"
Reload: "&aConfig reloaded. Changes should be live in game."

# Staff Chat
# Permissions: staffchat.use(allows the player to execute /staffchat) staffchat.see(allows the player to see the staff chat messages)

PrefixSC: "&8(&4StaffChat&8)&e&l"
Suffix: " &8» &f&l"
# {prefixsc}
Enabled: "{prefixsc} &7Toggle enabled"
Disabled: "{prefixsc} &7Toggle disabled"
NoPerm: "&cSorry you don't have permission!"

# Join Messages
# Add more with this: - ""

message:
    - "&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*"
    - " "
    - "                &eWelcome to &e&lYour&f&lServer&e!"
    - " "
    - "         &e&lDiscord - &fhttps://discord.gg/yourservercode"
    - "         &e&lStore - &fhttps://store.yourserver.net"
    - "         &e&lWeb - &fhttps://yourserver.net"
    - " "
    - "&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*&e*&f*"