# LinksCore Version: 1.7
# Support Discord: https://discord.io/RefracDev

# This is a debug option for the developers to use to help fix an issue easier
Debug:
  # Do you want it enabled or not?
  enabled: true

# Messages
Messages:
  enabled: true
  join_motd:
    - "&7&m----------------------------------------------------"
    - ""
    - "  &eWelcome &d{player}&e, to &dSERVER&e!"
    - ""
    - "&e&l» Discord: &dhttps://discord.gg/yourserver"
    - "&e&l» Teamspeak: &dts.yourserver.net"
    - "&e&l» Website: &dhttps://yourserver.net"
    - "&e&l» Store: &dhttps://store.yourserver.net"
    - ""
    - "&7&m----------------------------------------------------"
  # What should the messages be?
  first_join_message: "&eWelcome &d{player} &eto &dSERVER&e!"
  join_message: "&d{player} &ehas joined."
  silent_join_message: "&eWelcome back, &d{player}&e."
  quit_message: "&c{player} &ehas left."
  silent_quit_message: "&eGoodbye, &d{player}&e."
  noPermission: "&cSorry you don't have permission!"

# Links
# Add more with this: - ""
Links:
  - "&7&m----------------------------------------------------"
  - ""
  - "&e&l» Discord: &dhttps://discord.gg/yourserver"
  - "&e&l» TeamSpeak: &dts.yourserver.net"
  - "&e&l» Website: &dhttps://yourserver.net"
  - "&e&l» Store: &dhttps://store.yourserver.net"
  - ""
  - "&7&m----------------------------------------------------"