name: Links
version: '2.0'
main: me.refrac.links.Links
author: Refrac
description: Links plugin
website: https://discord.io/RefracDev

commands:
  links:
    description: Links command

permissions:
  links.silent.join:
    description: Allows the user to join silently
    default: false
  links.silent.quit:
    decription: Allows the user to quit silently
    default: false