name: LinksCore
# Change ${project.version} to 1.6.0 if not using maven
version: ${project.version}
main: me.refrac.linkscore.LinksCore
authors: [Refrac, RefracDev]
# Change ${project.description} to LinksCore Server Links and More! if not using maven
description: ${project.description}
commands:
  links:
    description: Main command
  linksreload:
    description: Reload command
  discord:
    description: Shows the server Discord
  store:
    description: Shows the server Store
  website:
    description: Shows the server Website
    aliases: [site, forum, forums]
  staffchat:
    description: Allows you to chat with your fellow staff members
    aliases: [sc, sctoggle]
  teamspeak:
    description: Shows the server Teamspeak
    aliases: [ts]