name: LinksCore
version: '1.7'
main: me.refrac.linkscore.Links
author: Refrac
description: LinksCore utility plugin
url: https://discord.io/RefracDev

commands:
  links:
    description: Links command