name: Links
version: '2.4.1'
main: me.refrac.links.Links
softdepend: [PlaceholderAPI]
author: Refrac
description: Links plugin by Refrac
website: https://discord.com/invite/mUKjWZByzQ

commands:
  links:
    description: Links command
  linksreload:
    description: Links Reload Command

permissions:
  links.silent.join:
    description: Allows the user to join silently
    default: false
  links.silent.quit:
    decription: Allows the user to quit silently
    default: false