name: LinksCore
version: '1.9'
main: me.refrac.linkscore.Links
author: Refrac
description: LinksCore utility plugin
website: https://discord.io/RefracDev

commands:
  links:
    description: Links command

permissions:
  sophos.silent.join:
    description: Allows the user to join silently
    default: false
  sophos.silent.quit:
    decription: Allows the user to quit silently
    default: false