name: Links
version: '2.0.2'
main: me.refrac.links.Links
author: Refrac
description: Links plugin by Refrac
website: https://discord.io/RefracDev

commands:
  links:
    description: Links command

permissions:
  links.silent.join:
    description: Allows the user to join silently
    default: false
  links.silent.quit:
    decription: Allows the user to quit silently
    default: false
  links.help:
    description: Shows the help page
    default: op
  links.about:
    description: Show the about page
    default: op
  links.reload:
    description: Reloads the config file
    default: op
  links.update:
    description: Updater permission
    default: op